variable "azure_locations_to_theatres" {
  description = "Mapping of Azure locations to their theatre of operations (EMEA, APAC, AMER)"
  type        = map(string)
  default = {
    # EMEA regions
    "North Europe"            = "EMEA"
    "West Europe"             = "EMEA"
    "UK South"                = "EMEA"
    "UK West"                 = "EMEA"
    "France Central"          = "EMEA"
    "France South"            = "EMEA"
    "Germany West Central"    = "EMEA"
    "Germany North"           = "EMEA"
    "Norway East"             = "EMEA"
    "Norway West"             = "EMEA"
    "Switzerland North"       = "EMEA"
    "Switzerland West"        = "EMEA"
    "Sweden Central"          = "EMEA"
    "Sweden South"            = "EMEA"
    "Italy North"             = "EMEA"
    "Poland Central"          = "EMEA"
    "Spain Central"           = "EMEA"
    "Austria East"            = "EMEA"
    "Belgium Central"         = "EMEA"
    "Denmark East"            = "EMEA"
    "South Africa North"      = "EMEA"
    "South Africa West"       = "EMEA"
    "UAE Central"             = "EMEA"
    "UAE North"               = "EMEA"
    "Qatar Central"           = "EMEA"
    "Israel Central"          = "EMEA"
    "Turkey West"             = "EMEA"

    # APAC regions
    "East Asia"               = "APAC"
    "Southeast Asia"          = "APAC"
    "Australia East"          = "APAC"
    "Australia Southeast"     = "APAC"
    "Australia Central"       = "APAC"
    "Australia Central 2"     = "APAC"
    "Japan East"              = "APAC"
    "Japan West"              = "APAC"
    "Korea Central"           = "APAC"
    "Korea South"             = "APAC"
    "Central India"           = "APAC"
    "South India"             = "APAC"
    "West India"              = "APAC"
    "Jio India West"          = "APAC"
    "Jio India Central"       = "APAC"
    "Indonesia Central"       = "APAC"
    "Malaysia West"           = "APAC"
    "New Zealand North"       = "APAC"
    "China East"              = "APAC"
    "China East 2"            = "APAC"
    "China East 3"            = "APAC"
    "China North"             = "APAC"
    "China North 2"           = "APAC"
    "China North 3"           = "APAC"

    # AMER regions
    "East US"                 = "AMER"
    "East US 2"               = "AMER"
    "West US"                 = "AMER"
    "West US 2"               = "AMER"
    "West US 3"               = "AMER"
    "Central US"              = "AMER"
    "North Central US"        = "AMER"
    "South Central US"        = "AMER"
    "Canada Central"          = "AMER"
    "Canada East"             = "AMER"
    "Brazil South"            = "AMER"
    "Brazil Southeast"        = "AMER"
    "Chile Central"           = "AMER"

    # US Government regions
    "US Gov Arizona"          = "AMER"
    "US Gov Texas"            = "AMER"
    "US Gov Virginia"         = "AMER"
    "US Gov Iowa"             = "AMER"
    "US Gov Utah"             = "AMER"
    "US Gov California"       = "AMER"
    "US DoD Central"          = "AMER"
    "US DoD East"             = "AMER"
  }
}
